# Generated by Django 5.2.4 on 2025-07-25 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 7, 25, 1, 48, 53, 119001, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
